name: Swift tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        simulator: ["iPad (8th generation)", "iPhone 8", "iPhone SE (2nd generation)", "iPhone 11", "iPhone 12 Pro Max", "iPhone 12 mini"]
    steps:
    - uses: actions/checkout@v2
    - name: iOS build and tests on ${{ matrix.simulator }}
      env:
        SIM: ${{ matrix.simulator }}
      run: xcodebuild test -scheme "SwiftWeekdays-Package" -destination "platform=iOS Simulator,name=$SIM"
